### ISSUE TITLE
Compatibility with tibble imputs

### ISSUE THREAD

**Issue by baarthur** [ipeaGIT/accessibility#49]
Hi there,

I have been using `{r5r}` and `{accessibility}` using the tidyverse approach with no major hiccups, except for the `cost_to_closest` function. As mentioned in issue https://github.com/ipeaGIT/accessibility/issues/48, `land_use_data` handles well `data.frames`, however, it does not accept a `tibble` input, which makes me need to convert it to a `data.table` before using the function. 

A reprex (I convert to `tibble` just to simulate my original data): 
```
library(accessibility)
library(data.table)
library(sf)

library(tibble)

data_dir <- system.file("extdata", package = "accessibility")
travel_matrix <- readRDS(file.path(data_dir, "travel_matrix.rds"))
land_use_data <- readRDS(file.path(data_dir, "land_use_data.rds")) %>% as_tibble()

mtc <- cost_to_closest(
  travel_matrix,
  land_use_data,
  opportunity = "schools",
  travel_cost = "travel_time",
  n = 1
)
```

throws the error
```
Error in `land_use_data[[col]]`:
! Can't extract column with `col`.
✖ Subscript `col` must be a location, not a character `NA`.
Run `rlang::last_trace()` to see where the error occurred.
```

It took me quite some time to figure out that the problem was my data not being in the `data.table` format, as the problem goes away if I convert my original data using `as.data.table`.

I don't know why this is happening, though, since according to `cost_to_closest`'s code between lines 14 and 23, anything that is not a `data.table` should be converted. In fact, `inherits(land_use_data, "data.table")` throws `FALSE` in the example above. Any clue why this is not working?

**Comment by dhersz** [comment]
Hi @baarthur, thanks for opening the issue.

The issue was actually on `assert_land_use_data()`, prior to converting the data, because tibbles have stricter subsetting constraints than data.tables and data.frames.

https://github.com/ipeaGIT/accessibility/commit/54a42f30376c4464be7c41244723bbc837b29a70 should have fixed the error. Can you please try running the same example above with the development version? You can install it with `remotes::install_github("ipeaGIT/accessibility")`.

Please let me know if you face any problems. Cheers.

**Comment by baarthur** [comment]
Hey @dhersz, thanks for the fast reply! Running smoothly now.
